### ISSUE TITLE
react 15.5 upgrade

### ISSUE THREAD

**Issue by modosc** [imgix/react-imgix#101]
i think it's just `{ PropTypes }` -> `prop-types`, testing now

**Comment by modosc** [comment]
also some warning from other packages:

glenjamin/skin-deep#86

**Comment by modosc** [comment]
#104 should solve the other warnings. 

@frederickfogerty at this point would we just bump up the react requirements to 15.5 and bump the major version or is there other refactoring you had in mind?

**Comment by frederickfogerty** [comment]
@modosc I was going to bump the minimum react requirement to 15.0.

I also had something else I wanted to refactor as this was a breaking change. There is a deprecated prop which we can now remove since we're making a breaking change. https://github.com/imgix/react-imgix/blob/master/src/index.js#L41

**Comment by modosc** [comment]
@frederickfogerty i'm happy to take this on to get a release ready - is it just the above items?
