### ISSUE TITLE
SSR markup does not contain image src attribute

### ISSUE THREAD

**Issue by Krucial92** [imgix/react-imgix#139]
**type:** bug

**react-imgix version:** `v7.1.1`

**Code**

```
<img src={getImgixUserPicture(this.props.auth.user.picture)} />
<Imgix
      alt="user"
      auto={['compress']}
      src={getImgixUserPicture(this.props.auth.user.picture)}
      type="img"
      width={40}
      height={40}
/>
```

**Expected behavior:**
I am server-side rendering my whole application, when my HTML markup is generated the image src tag does not exist. In the example code above I have provided a normal image tag as well as one with Imgix, and the rendered markup is different between the two. For example my code above generates the following markup (please note the second image has no src tag):
```
<img src="https://mysite-dev.imgix.net/avatars/2018/6/f5946b91-7579-4b1d-852b-91fbdb99bab4.jpeg"/><img width="40" height="40"/>
```

**Actual behavior:**
I would expect that react-imgix would generate the same markup that a normal image tag would regardless of being rendered on the server.

React Version: 16.4

**Comment by frederickfogerty** [comment]
Hey @Krucial92 👋 thanks for the bug report! Due to the 2-step render that this component undergoes in order to work out the rendered size on the client, it renders an empty image on the first pass.

For server rendering to work the way you intend, use the `aggressiveLoad` prop, e.g. `<Imgix aggressiveLoad src="..." />`.

Please let me know how this goes for you. We're in the process of updating the documentation for this library in order to make it easier for people to understand what combination of props to use.

**Comment by Krucial92** [comment]
Hey @frederickfogerty, thanks so much for your quick reply and resolution. I'm sorry I must have missed that option when I was scrolling through the available props (duh, my bad).

Have just used `aggressiveLoad` and it generates the markup perfectly as expected.

Thanks for the library, and your help. Cheers.

**Comment by frederickfogerty** [comment]
All good @Krucial92, I'm going to close this now as it seems to be resolved. I'll look to add an example usage for server-side rendering in the docs.
