### ISSUE TITLE
Server-Side Rendering srcSet generation performance bottleneck

### ISSUE THREAD

**Issue by tstirrat15** [imgix/react-imgix#328]
When profiling our isomorphic React app, one thing that we noticed was that srcSet generation was taking up a whole lot of CPU time - somewhere between a third and a half of the total cpu render time on a page that had 17 images.

Here's a [`node-clinic` flamegraph](https://upload.clinicjs.org/public/b504341d486f38f96cea706cce88906329b7fdc576d8d105dacd36f1e9cc593a/9042.clinic-flame.html#selectedNode=3007&zoomedNode=&exclude=83c0&merged=true) showing the problem.

We were able to work around the problem by disabling srcset generation on the backend, especially because the images that were being sent from the backend were LQIPs, and it didn't make sense to have a full srcset for those, but the amount of CPU time consumed by generating srcSets was surprising to me.

Has this already been optimized, and it's just an inherently expensive operation? Or are there gains to be made in optimizing the srcSet generation code?

**Comment by sherwinski** [comment]
Hi @tstirrat15 thanks for bringing this up. As far as I know, srcset generation has not been exhaustively optimized so perhaps there are gains to be made there. I won't be able to dedicate time to look into this just yet, but would happily review a PR or discuss anything you come across if you have the time and want to look into it.

**Comment by sherwinski** [comment]
hey @tstirrat15,

There have been numerous performance changes made to URL building (all credit goes to @baldurh) since this issue was first opened. I would invite you, or anyone else who's curious, to test these out in the latest release. I'm going to go ahead and close this issue now, but feel free to comment back with any questions you may have.

Also relates to #406, #414, #418

**Comment by tstirrat15** [comment]
Thank you!
