### ISSUE TITLE
Background Images no longer displaying in v8.6.0

### ISSUE THREAD

**Issue by dustinbrink** [imgix/react-imgix#341]
**Describe the bug**
Background images no longer display in react-imgix v8.6.0

**To Reproduce**
created a sample to reproduce here https://codesandbox.io/s/109766y434

```js
      <Background src="https://assets.imgix.net/examples/pione.jpg">
        <h2>Blog Title</h2>
      </Background>
```

**Expected behaviour**
Background images load and display

**Information:**
- react-imgix version: 8.6.0
- browser version: Chrome 73

**Additional context**

**Comment by sherwinski** [comment]
Hi @dustinbrink thanks for catching this, looks like this is being caused by a dependency regression with react-measure. See in [this demo](https://codesandbox.io/s/zk86221wq4) that when we downgrade react-measure to v2.2.5 or lower it will work, but not for v2.2.6
I'm going to cut a patch pinning react-measure to version <2.2.6 and bring this up with the project maintainers.

**Comment by dustinbrink** [comment]
Great, thanks!
