### ISSUE TITLE
Component API differs from underlying Imgix API

### ISSUE THREAD

**Issue by eahlberg** [imgix/react-imgix#446]
While [it is explained](https://github.com/imgix/react-imgix/blob/master/README.md#basic-use-case) that the `fit` prop defaults to `crop`, this differs from the [documentation](https://docs.imgix.com/apis/url/size/fit) where the default value for `fit` is `clip`. Is there a reason for this? I would have expected the component to follow the defaults from the official API.

**Comment by frederickfogerty** [comment]
Hey @eahlberg, I was waiting for some others to jump in here, but due to the silence, I'll add my 2 cents. 

The real explanation for this is that initially, this component was further away from the imgix API, and it performed more magic to try enhance the developer experience. Over the years, as browsers and imgix have involved, this component has not needed to do as much. A big change here for example, was the srcset + sizes update. 

Looking at the [source code](https://github.com/imgix/react-imgix/blob/master/src/react-imgix.jsx#L195), it seems that by default `fit` will actually be `false` (which then uses `clip`). It then only sets `fit=crop` if a `crop` param is passed. This is to help the developer as without `fit=crop`, `clip` has no effect.

`fit=crop` is only used by default in the background component: https://github.com/imgix/react-imgix/blob/15b0073f7b14679ebd6c43c1cf79bfb9c64b35c2/test/integration/react-imgix.test.jsx#L562

cc @sherwinski

**Comment by eahlberg** [comment]
Hey @frederickfogerty, thanks for the prompt response and for the explanation! 🙏

I took a look myself and I'm not really sure the `Imgix` component defaults to `fit=clip`. [Here's a test which fails for me locally](https://github.com/eahlberg/react-imgix/commit/b1a15f5221324c72cc3c9636ed4aacf9c56f0c51) which I would expect to pass in that case.

My guess for why would be because of [this](https://github.com/imgix/react-imgix/blob/master/src/react-imgix.jsx#L22-L25) and [this](https://github.com/imgix/react-imgix/blob/master/src/react-imgix.jsx#L196).

With that said (and if what I have stated above is correct), I guess this is a breaking change so I'm not sure if you'd like to change the behavior and how you'd handle the implications of that.

**Comment by frederickfogerty** [comment]
All good @eahlberg.

You're right, that test does fail locally because it doesn't pass `fit=clip`, it passes `fit=false` (at least on inspection, I haven't tested this). Maybe you could check if that is the case? If it is indeed `fit=crop`, then this would be a candidate for something to change with the new major version of this library, imo. 

Thanks for digging into the source code to find the cause 👍

We don't specifically have a breaking change policy, but we do try keep them as infrequent as possible (think every 6 months).

It seems to me that this wouldn't actually be so bad of a breaking change, because choosing `clip` or `crop` without specifying a width or height doesn't have an effect. I think if people provide both width and height, we should still set `fit=crop` by default. Thus, this breaking change shouldn't actually be a breaking change for most eople.

**Comment by sherwinski** [comment]
Thanks for pointing this out @eahlberg and for investigating. I think you're correct in that we are defaulting to `fit=crop` -- which my local tests also reflect. It definitely makes sense that we should to default to `clip` (or even leave it unspecified) unless the user enters in a width and/or height, in which case we use `fit=crop`.

And even if this does result in a breaking change, I don't think that should really stop us from doing it. It's sort of high time for a major release I'd say, and it'll give a good opportunity to clean up some deprecated code in the meantime. As @frederickfogerty already pointed out, it shouldn't be that noticeable of a change anyways.
I'll need to take some time and think about the different scenarios/how we want to trade off the user experience when using this component vs staying close to the imgix API, but overall agree with the sentiments everyone here has expressed.

PS thanks for jumping in on this @frederickfogerty
