### ISSUE TITLE
Picture support not working

### ISSUE THREAD

**Issue by luizcieslak** [imgix/react-imgix#495]
**Before you submit:**
v 9.0.0

- [x] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

Isolated problem here: 

**Describe the bug**
Discovered the lib today, tried to use the `Picture` element to render responsive images exactly as the documentation but the image is not rendering. It seems that only the fallback is displaying.

**To Reproduce**
Just copy the `Picture` example in documentation and use a imgix image as `src`.
Check it here: https://codesandbox.io/s/vigorous-http-3b7s2

```js
// A *self-contained* demonstration of the problem follows...
// This should be able to be dropped into a file with react-imgix installed and just work
      <Picture>
        <Source
          src={src}
          width={400}
          htmlAttributes={{ media: "(min-width: 768px)" }}
        />
        <Source
          src={src}
          width={200}
          htmlAttributes={{ media: "(min-width: 320px)" }}
        />
        <Imgix src={src} width={100} />
      </Picture>
```

Steps to reproduce the behaviour:

1.  Copy `Picture` example from docs
2.  replace src with an imgix image
3.  See error

**Expected behaviour**
It should behave as described in [this link](https://docs.imgix.com/tutorials/using-imgix-picture-element)

**Screenshots**
![image](https://user-images.githubusercontent.com/14146176/68715873-b8594680-0581-11ea-93e3-572a41f6748b.png)

**Information:**

- react-imgix version: 9.0.0
- browser version: Codesandbox browser

**Additional context**
none

**Comment by sherwinski** [comment]
Hey @luizcieslak, sorry for the delayed response. I'm currently investigating this issue and hope to have some updates for you soon.

**Comment by sherwinski** [comment]
So this actually looks to be expected, please see this example that reproduces the same behavior with HTML elements:
https://codesandbox.io/s/bug-fallback-img-with-picture-7722l
In this example, each of the `<Source>` elements and the fallback `<img>` are color coded using the `mono` parameter to show switching between them as the browser is resized. 

It seems that we are actually correctly switching between elements as expected, the actual problem being that the chosen image is constrained to the space occupied by the fallback `img`. This understandably makes it difficult to identify if switching ever occurs and gives the impression that only the fallback `img` is ever shown. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) this behavior is expected:

> The selected image is then presented in the space occupied by the `<img>` element.
-----
Which leads me to the root cause. The `width={100}` prop in the fallback `<Imgix>` component is being passed as an attribute to the `<img>` that it renders. This is constraining whatever image is chosen by the browser to be 100 pixels. A possible solution is to include the width as an `imgixParam` instead:

```js
<Imgix
	src={src}
	imgixParams={{
            w: 100
          }}
/>
```

Unfortunately, the problem here is that `<Imgix>` won't build out a fixed-size `srcset` if the width is passed in this way. That means that when using a fallback image, it will resize itself with the browser instead of staying fixed.
@frederickfogerty @jayeb I wonder if it's worth adding logic to check for `w` and `h` in `imgixParams` when determining when to generate fixed-size srcsets. We already do with `ar` as we don't expect aspect ratio to be passed via its own prop.

**Comment by luizcieslak** [comment]
it works with your possible solution: 
```
<Imgix
	src={src}
	imgixParams={{
            w: 100
          }}
/>
```
https://codesandbox.io/s/still-firefly-ldw6s


Gonna open a PR updating the documentation. Thanks!
