### ISSUE TITLE
Cannot specify min or max width/height

### ISSUE THREAD

**Issue by willcosgrove** [imgix/react-imgix#62]
The width and height params have default values specified by the Imgix component, and appear to take precedence over the min-h, min-w, max-h, max-w params when processed on Imgix.

The end result is, you may be able to specify the min-w, etc.  And it will show up in the URL.  But because the `w` and `h` params are _also_ specified, the min/max params get ignored.

**Comment by frederickfogerty** [comment]
Hey @willcosgrove. Thanks for the feedback 😄 . Can you elaborate a bit more on what you're using `min-w` and `min-h` for? If we can understand the use-case for those options, we can design a better solution for this, or use something that is already implemented.

**Comment by ultimagriever** [comment]
Was this actually solved or just closed? Because I'm trying to use `max-w` and `max-h` as well and it's not working, they're not being passed to the URL at all. I want the user to be able to upload images with any dimensions and ratios, but they can't overflow a component's boundaries, hence the `max-w` and `max-h`.
