### ISSUE TITLE
Intro + React Questions

### ISSUE THREAD

**Issue by paulstraw** [imgix/react-imgix#7]
Hey @frederickfogerty, I'm Paul Straw. I'm handling Developer Relations at imgix now, so I'll be working with you a bit to help continue improving react-imgix.

We recently had a customer raise a couple questions about react-imgix, and I wanted to run them by you and hopefully get your thoughts:

* React 0.14 requirement: Do you have any sense of what React 0.13 vs 0.14 usage looks like? I dug on this for a bit, but it doesn't seem to be well-documented, unfortunately. Personally, I think keeping the react-imgix 1.0.4 version around is probably fine, just wanted to see if you have any idea whether this could be a common issue.
* Babel requirement: How would you feel about including a pre-built version of the library to support people who either aren't using Babel, or are using a more limited subset of its features?

I'm happy to implement either of these myself, but at least wanted to get your thoughts before jumping in.

Thanks!
-paul

**Comment by frederickfogerty** [comment]
Hey Paul!

Congratulations on the new position.

Off the top of my head (I can’t check the repo as I’m on holiday at the
moment), there should be no significant differences in usage between React
0.13 and React 0.14, but only versions below v2(?) are supported on React
0.13 as v2 introduced a React-dom dependency, to migrate to the new api in
0.14.

The only differences I can think of are the lack of srcset generation on
v1, and potentially some real minor changes.

I’m not sure if there’s anything to change there. I would probably shy away
from maintaining a React 0.13 branch, but if you have to, you could
probably abstract away the different parts and keep the core the same. You
could do this with a build tool which you could use to conditionally build
either a React 0.13 or 0.14 version.

The npm version already uses a pre-built version as the default source, as
is very standard practice in the industry. It is not included in the git
repo because I wanted to keep it clean, but if you want to remove it from
.gitignore, that’s completely fine.

Feel free to contact me if you have any more questions
Fred

P.S. Ask Kelly about that t-shirt :)

**Comment by paulstraw** [comment]
Awesome, thanks Frederick. Email me paul@imgix.com with your size, color (gray, blue, orange), and address and i'll get the shirt sorted. 😁
