### ISSUE TITLE
Duplicate attributes when using "attributeConfig"

### ISSUE THREAD

**Issue by michaelmarconi** [imgix/react-imgix#738]
Hi – I'm trying to get Lazy Loading working by following the instructions at:  https://github.com/imgix/react-imgix#lazy-loading

These state:
> In order to use react-imgix with lazysizes, you can simply tell it to generate lazysizes-compatible attributes **instead of** the standard src, srcset, and sizes by changing some configuration settings

Note that it says "instead of", whereas the output in my browser now has both the original attributes (`src`, `srcSet`, `sizes`) **AND** the data attributes (`data-src`, `data-srcset` & `data-sizes`).  That is creating a large amount of extra code which seems unnecessary to me.

Here's my code:

```jsx
      <Imgix
        src={`https://[REDACTED].imgix.net/${imagePath}`}
        sizes={sizes}
        className={`lazyload ${className}`}
        attributeConfig={{
          src: "data-src",
          srcSet: "data-srcset",
          sizes: "data-sizes",
        }}
      />
```

Am I correct to expect only the data attributes and if so, what am I doing wrong?

**Comment by frederickfogerty** [comment]
Hi there @michaelmarconi. In fact, the documentation is correct - `react-imgix` only sets `data-src`, `data-srcset`, and `data-sizes` instead of `src`, `sizes`, and `srcset`. It is actually lazysizes that does the copying once the page is loaded. 

> That is creating a large amount of extra code which seems unnecessary to me.

When you mention this, is this seen as an explicit problem for you? Since this "duplication" happens on the client side, I would say that there is not much downside to this.

> Am I correct to expect only the data attributes and if so, what am I doing wrong?

You are to expect the `data-*` attributes in the page source, and then once the page loads, lazysizes should copy the attributes over. You're not doing anything wrong here.

We're open to suggestions but at this stage I don't see a clear path forward to improving this, so I'm going to close this. I'm happy to reopen this to discuss further.
