### ISSUE TITLE
Multiple images downloaded in Safari using Imgix component

### ISSUE THREAD

**Issue by mwisner** [imgix/react-imgix#786]
**Describe the bug**
When using safari, the images generated seem to be downloaded twice in Safari.

Something like this:
```js
      <Imgix src="https://assets.imgix.net/unsplash/bridge.jpg" />
```
always seems to download at least two images. In chrome, it only downloads one

**To Reproduce**
Code Sandbox: https://codesandbox.io/s/exciting-wildflower-hbw2j?file=/package.json

**Expected behaviour**
In chrome only a single image is downloaded, but 
**Screenshots**
![Screen Shot 2021-05-18 at 8 31 08 AM](https://user-images.githubusercontent.com/201416/118651434-8c8cd180-b7b3-11eb-8f2f-8e8ae8032382.png)

**Information:**
Device: MacOS 11.2.3
Safari: 14.0.3
React: 17
React-Imigix: 9.1.1

**Comment by frederickfogerty** [comment]
Hi there @mwisner! Thanks for opening this issue. This is a [known issue](https://bugs.webkit.org/show_bug.cgi?id=190031) with Safari and as such there is nothing actionable we can do on our end. Sorry about this and I hope they fix the issue soon!

**Comment by nicolasdanelon** [comment]
Hi @frederickfogerty is it posible on mobile that react-imgix download the largest image? I don't want to start a new issue if this is part of this bug here.

**Comment by frederickfogerty** [comment]
@nicolasdanelon in the issue I linked it mentions that the bug was verified on iOS, so I imagine so. To be clear, this is not an issue with react-imgix - any React app will suffer from these issues. If this is a significant issue, I would suggest to wrap react-imgix in another component that sets the `srcset` on the first render, and then sets `src` after a short delay/next render.
