### ISSUE TITLE
+ symbol gets converted into it's corresponding code %2B in generated src and srcset

### ISSUE THREAD

**Issue by wolfian** [imgix/react-imgix#808]
**Description:** I'm trying to use _react-imgix_ for images getting served through _Prismic CMS_ on my _Gatsby_ site. Issue is, case where image url contains a **+** symbol. It get converted to it's corresponding symbol **%2B** in the generated **src** and **srcset**, resulting in failure to get the image. 

The issue I faced was using this url: [https://images.prismic.io/pestcontrol/eb5bfdc4-327a-44a3-afb0-7cc2b257fad1_slide+1.png?auto=compress,format](https://images.prismic.io/pestcontrol/eb5bfdc4-327a-44a3-afb0-7cc2b257fad1_slide+1.png?auto=compress,format)
(the **+1** in the end get's replaced with **%2B1**)

**Code snippet used:**
```
<Imgix
        src="https://images.prismic.io/pestcontrol/eb5bfdc4-327a-44a3-afb0-7cc2b257fad1_slide+1.png?auto=compress,format"
        imgixParams={{
            format: "auto",
            fm: "webp",
            fit: "crop",
            ar: "16:9",
        }}
        sizes="(max-width:576px) 640px, (max-width:991px) 1280px, 100vw"
        className="lazyload"
  />
```

Any idea what could be done to prevent that from happening?

**Image attached:**
![2021-08-12_19-10](https://user-images.githubusercontent.com/26486080/129207604-8ed141b0-31d9-4fad-ae21-bb78a67c6f53.png)

**Comment by frederickfogerty** [comment]
Hi @wolfian 👋 thanks for opening this issue. 

The problem here is that the `src` prop expects the url to be unencoded, whereas the `+` symbol in your url is actually an encoded space. react-imgix cannot tell whether this `+` is meant to be an encoded space, or should be encoded again (to represent an actual `+`), so it encodes it.

The solution here is to decode the `+` before passing it to react-imgix. You can do this like so:

```js
const ImgixClient = require('@imgix/js-core');

const encodedURL = "https://images.prismic.io/pestcontrol/eb5bfdc4-327a-44a3-afb0-7cc2b257fad1_slide+1.png?auto=compress,format";
const unencodedURL = encodedURL.replace("+", " ");

console.log(ImgixClient._buildURL(encodedURL)); // logs broken URL
console.log(ImgixClient._buildURL(unencodedURL)); // logs working URL
```

You can play around with this code here: https://runkit.com/frederickfogerty/encoding-issue-in-react-imgix

Please let me know if you have any more issues with this. Thanks!

**Comment by kupe517** [comment]
@frederickfogerty How would I use with this `<Imigix>` component? 

I am having the same issue. When I pass a src to Imigix component that has a + in the name it encodes the + symbol to `2%2B%25`, but I don't want it to be encoded.

**Comment by sherwinski** [comment]
Hey @kupe517 you may want to follow the discussion over at #815, which sounds like is related to the issue you are having.
