### ISSUE TITLE
Imgix doesn’t check if the there’s a value available in the prop before trying to process the src url

### ISSUE THREAD

**Issue by jakio** [imgix/react-imgix#813]
Imgix should check if the value provided to src is actually a string before trying to process it. 

To prevent this causing an unhandled exception it's necessary to set a fallback image url.

**Comment by frederickfogerty** [comment]
Hi there @jakio 👋 Fred from imgix here - thanks for the issue report. This library defines `src` as a string and also as required in the component's prop types, and also in the Typescript type definitions, therefore we expect the user to use the component under these constraints. If the value passed to `src` is not a string, this does not comply with these constraints. If we were to handle other types, this would become an open-ended issue, therefore we won't be fixing this issue. Please let me know if you have any further thoughts.

**Comment by lmcorreia** [comment]
Hi @frederickfogerty, while I understand the position on the constraint, it seems to me the component could gracefully handle an invalid `src` value by ignoring it or force casting it to a String.

This would allow the component to keep its current TS types and propTypes while not forcing the whole application into an error state or requiring the developer to wrap the component in a React ErrorBoundary in case something like `undefined` is passed by mistake.

If you're willing to concede on this, I can have a go at proposing the changes on a Pull Request. Sounds like you can have your cake and eat it too 😃

**Comment by frederickfogerty** [comment]
Hi @lmcorreia 👋 I appreciate the offer to help here! Technically, I think it is actually quite easy to fix the code-level issue, but I think the issue comes when deciding what behaviour the component should have in this undefined state. In the past we've had issues where invalid image sources cause the whole site to be requested (in Safari for example).

I can think of two things to do here, both of which are not perfect:

- render nothing (not great for page flow)
- render an image with no `src` (the image is invalid).

If you would like to come back with some other suggestions, I would be happy to evaluate them and see if there's a viable solution here.

**Comment by lmcorreia** [comment]
Thanks for looking into this, @frederickfogerty. I think either returning `null` from render or rendering an image with no `src` are both acceptable in this context. Rendering an error message would also be an option, I guess.

But in any case, any of these is still better IMO than letting the `src` value flow through to https://github.com/imgix/react-imgix/blob/637cbcf0378cd3debda762e2a916325be1a0474e/src/extractQueryParams.js#L2 where it'll cause un unhandled exception when trying to call the `split` method - that's the real bummer here.

It could also cause some additional problems down the line but as long as they are contained to a reasonable point, I don't think it matters much what is ultimately rendered when the types aren't respected. So, to reiterate, the core issue here I think is just that Error that inevitably gets thrown. If you're loading some async data to get determine which `src` to pass to the component and you forget to put the component rendering in a conditional, you can easily get into that situation.

**Comment by frederickfogerty** [comment]
Hi @lmcorreia, thanks for the thoughtful discussion. I've been on vacation and have also spent some time discussing this with my team, which has caused the delayed response here. I want to respond to your comment and then give my current stance on this.

> I think either returning null from render or rendering an image with no src are both acceptable in this context. Rendering an error message would also be an option, I guess.

I think returning `null` from render could cause layout issues, since no `img` would be rendered in some cases which could cause layouts to shift/display weirdly while the `src` was incorrect.

Rendering an image with no `src` is non-starter due to the issue mentioned with Safari - the worst thing would be to display a broken image or load the whole page again - which would cause more issues.

Rendering an error message is not a great experience to the website visitor if they ever get to see the image.

> So, to reiterate, the core issue here I think is just that Error that inevitably gets thrown.

I think this is where I disagree with you. Exceptions and handling them are just a natural part of using JS and there are other errors that could be thrown and would need to be handled gracefully. Swallowing these error states just delays the problem and means it's even less likely that the issue will be handled by the developer. My colleague said this: "If we swallow error states (or log them) for people, then I think it’s less likely they get around to fixing things (not to mention, something like this should be caught in their testing layer)." - I completely agree with this.

> If you're loading some async data to get determine which src to pass to the component and you forget to put the component rendering in a conditional, you can easily get into that situation.

In this case I would probably be using some loading indicator anyway, since the src isn't available.

---

Another aspect here is that it's a slippery slope to start to try to handle non-string values. For example, if we called `String(src)` to try to coerce the value to a string, this could fail in non-obvious ways, which could cause the application to fail in a non-graceful way. The better strategy is that the value passed to us is what is expected, and then we are sure we can handle it.

My current stance is that there's no nice way to gracefully handle the error state, and also that by swallowing the error it creates a state where a potential error state is not handled, which in the end hurts the end-user experience.
