### ISSUE TITLE
Version 9 over-encodes file paths for Background Images

### ISSUE THREAD

**Issue by timscullin** [imgix/react-imgix#863]
This is already resolved in #815 but is still an issue for background images.

When using a background image with a space in the url, it may get stored in the database encoded, then re encoded using the imgix background script.

This has been resolved with `disablePathEncoding ` for `<Imgix>` components, but not for `<Background>`.

It would be great if the same solution worked for background 🙏

**Comment by sherwinski** [comment]
Hey @timscullin thanks for opening this issue. Our team has noted this issue and we'll set some time to look into this in the next few weeks. I'll post any updates here in the meantime.

**Comment by luqven** [comment]
Hey @timscullin, following up on this briefly.

Looks like we could update `react-imgix-bg.jsx`'s `renderSrc()` [function](https://github.com/imgix/react-imgix/blob/a16b841d40dbfd11bacf0311291747dbff06efac/src/react-imgix-bg.jsx#L155-L168) on line 155 to be something like:

```jsx
    const renderedSrc = (() => {
      const [rawSrc, params] = extractQueryParams(src);
      const longImgixParams = {
        ...params,
        fit: "crop",
        ...imgixParams,
        ...(disableLibraryParam ? {} : { ixlib: `react-${PACKAGE_VERSION}` }),
        width,
        height,
        dpr,
      };
      const srcOptions = { disablePathEncoding };
      return constructUrl(rawSrc, longImgixParams, srcOptions);
    })();
```

We'd also need to add some tests to [`encoding.test.ts`](https://github.com/imgix/react-imgix/blob/main/test/unit/encoding.test.js) to ensure this prop is getting registered in the background component.

If you, or anyone else, feel comfortable opening up a PR, I'd be happy to review it and provide feedback. Ideally, something similar would be done with the `Picture` component.

Otherwise, I can't tell you exactly when, but it seems like something we can tackle in the near future.
