### ISSUE TITLE
width and height don't do the right thing when they differ from width and height of sources

### ISSUE THREAD

**Issue by modosc** [imgix/react-imgix#90]
moved from [here](https://github.com/imgix/react-imgix/issues/45#issuecomment-288206488)
> Edit: issue seems to be coming from the generated fallback <img> element with the Picture Support. You need to define the width/height of the image on the parent <Imgix/> element otherwise it will load the 1x1 version by default on the fallback <img>! (crashing Safari/mobiles if you have big images by default).

something else i noticed yesterday in my work's codebase - you not only have to have a width/height on the parent element but it also needs to be the maximum width/height of any of the `<source>` elements that may be inside of the generated `<picture>`. so this:
```
<Imgix type="picture" src={src} width={100} height={100}>
  <Imgix type="source" src={src} width={400} height={100} imgProps={{ media: '(min-width: 768px)' }} />
</Imgix>
```

will load the 400x100 image on a large screen but will only display it as 100x100 (at least in chrome and safari)

i _think_ this is a bug - in my local testing setting the provided height/width on the fallback image but changing the same attributes on the parent container to the maximum values did the right thing everywhere. working around it doesn't seem hard but it's unclear if that's the expected behavior though. should i just open a new bug to discuss this?

**Comment by frederickfogerty** [comment]
Exposing a prop like fallbackImageDimensions could be a good idea here to set the fallback dimensions, and have the width and height set the picture element's props (as it does now).

Thoughts @modosc?

**Comment by modosc** [comment]
> Exposing a prop like fallbackImageDimensions could be a good idea here to set the fallback dimensions, and have the width and height set the picture element's props (as it does now).

sorry i dropped this thread. 

i think that may be more complicated than we need since it requires some forethought on the user's part. in my testing (and in our codebase) just taking the max height/width passed in for the parent solves this problem.

**Comment by frederickfogerty** [comment]
I've been thinking about this a bit and I think the best solution here is to require the user to pass a fallback `img` in all cases, rather than providing one for them. In pure HTML users are required to provide a fallback `img`, so this is actually closer to the spec than what we have. This allows us to use the `width` and `height` parameters for what they should be - setting the width and height of the parent component (and potentially automatically calculating this if it's not passed).

Other solutions I've thought of:
- Adding a `fallbackImageDimensions` prop for picture support
- Making the `width` and `height` props apply to the fallback only, and generating the width and height of the parent dynamically behind the scenes.

I think the first solution is the best of these options. Do you have any other thoughts @modosc?

**Comment by frederickfogerty** [comment]
This will be fixed in the next major version, 8.
